[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["cd backend && npm ci --only=production"]

[phases.build]
cmds = ["cd backend && npm run build || echo 'No build step needed'"]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"