[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = {
  NODE_ENV = "production",
  HOST = "0.0.0.0",
  PORT = "$PORT",
  RATE_LIMITING_ENABLED = "true",
  AI_MODELS_ENABLED = "true",
  CITYPULSE_ENABLED = "true", 
  QUANTUM_SWARM_ENABLED = "true",
  VELOCITY_SWARM_ENABLED = "true",
  WEBSOCKET_ENABLED = "true",
  LOG_LEVEL = "info"
}

[networking]
allowedHosts = ["*"]

[scaling]
autoscaling = true
minReplicas = 1
maxReplicas = 5
targetCPUUtilization = 70
targetMemoryUtilization = 80

[resources]
cpu = "500m"  # 0.5 vCPU
memory = "512Mi"  # 512MB RAM

[monitoring]
healthcheck = true
logs = true
metrics = true

[security]
allowPublicNetworking = true