# Prometheus configuration for FlowMind Universal Backend

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FlowMind Backend API
  - job_name: 'flowmind-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Health check endpoints
  - job_name: 'health-checks'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/health'
    scrape_interval: 30s
    
  # Frontend health checks (if they expose metrics)
  - job_name: 'frontend-citypulse'
    static_configs:
      - targets: ['citypulse.flowmind.app:443']
    scheme: https
    metrics_path: '/health'
    scrape_interval: 60s

  - job_name: 'frontend-flowmind'
    static_configs:
      - targets: ['flowmind.app:443']
    scheme: https
    metrics_path: '/health'
    scrape_interval: 60s

  - job_name: 'frontend-quantum'
    static_configs:
      - targets: ['quantum.flowmind.app:443']
    scheme: https
    metrics_path: '/health'
    scrape_interval: 60s

  - job_name: 'frontend-velocity'
    static_configs:
      - targets: ['velocity.flowmind.app:443']
    scheme: https
    metrics_path: '/health'
    scrape_interval: 60s